### ISSUE TITLE
Sampling from pre-trained model

### ISSUE THREAD

**Issue by Crista23** [HanGuo97/MultitaskSimplification#8]
I use the command below to sample from the pre-trained model:

        python run.py --mode decode --decode_ckpt_file NewselaFinalMTL/model-final --decode_data_dir decode/test_file.src --decode_output_file output.txt --log_root logs --exp_name test --soft_sharing_coef 0.1 --vocab_path cnn-dailymail/finished_files/vocab --batch_size 32 --beam_size 5 --max_enc_steps 5 --max_dec_steps 5 --steps_per_eval 5 --lr 0.01

However, I get the following error:

Task Newsela is using SummarizationModel
Task SNLI is using SummarizationModel
Task PP is using SummarizationModel
Loading Decoding Data from MultitaskSimplification2/decode/test_file.src 
max_size of vocab was specified as 50000; we now have 50000 words. Stopping reading.
Finished constructing vocabulary of 50000 total words. Last word added: 18:19
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/usr/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/usr/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "MultitaskSimplification/pointer_model/batcher.py", line 341, in fill_example_queue
    (article, abstract) = input_gen.next()
  File "MultitaskSimplification/pointer_model/batcher.py", line 423, in text_generator
    e = example_generator.next()  # e is a tf.Example
  File "MultitaskSimplification/pointer_model/data.py", line 139, in example_generator
    example_str = struct.unpack('%ds' % str_len, reader.read(str_len))[0]
MemoryError

Creating SummarizationModel 	Newsela Model
INFO:tensorflow:Building graph...
TODO: Using tf.where to replace tf.cond in next_cell_input
change sampled_tokens not include <start>?
INFO:tensorflow:Time to build graph: 2 seconds
2020-05-05 14:35:23.921164: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
INFO:tensorflow:Restoring parameters from MultitaskSimplification/NewselaFinalMTL/model-final
Traceback (most recent call last):
  File "run.py", line 482, in <module>
    tf.app.run()
  File "/home/usr/anaconda2/lib/python2.7/site-packages/usr/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "run.py", line 475, in main
    setup_and_run_decoding(FLAGS, hps)
  File "run.py", line 452, in setup_and_run_decoding
    decoder.decode(ckpt_file=FLAGS.decode_ckpt_file)
  File "MultitaskSimplification/pointer_model/decode.py", line 63, in decode
    misc_utils.load_ckpt(self._saver, self._sess, self._ckpt_dir, ckpt_file)
  File "MultitaskSimplification/utils/misc_utils.py", line 64, in load_ckpt
    saver.restore(sess, ckpt_file)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [50000] rhs shape= [29131]
	 [[Node: save_1/Assign_11 = Assign[T=DT_FLOAT, _class=["loc:@Newsela_Attention/policy/rnn/logits_kernel/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Newsela_Attention/policy/rnn/logits_kernel/bias, save_1/RestoreV2_11)]]

Caused by op u'save_1/Assign_11', defined at:
  File "run.py", line 482, in <module>
    tf.app.run()
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "run.py", line 475, in main
    setup_and_run_decoding(FLAGS, hps)
  File "run.py", line 449, in setup_and_run_decoding
    decoder.build_graph(decode_sess)
  File "/srv/disk01/usr/TS/models/MultitaskSimplification/pointer_model/decode.py", line 57, in build_graph
    self._saver = tf.train.Saver()
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 439, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 160, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
    use_locking=use_locking, name=name)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/usr/anaconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [50000] rhs shape= [29131]
	 [[Node: save_1/Assign_11 = Assign[T=DT_FLOAT, _class=["loc:@Newsela_Attention/policy/rnn/logits_kernel/bias"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Newsela_Attention/policy/rnn/logits_kernel/bias, save_1/RestoreV2_11)]]

**Comment by HanGuo97** [comment]
Hmm, I don't remember seeing this error. But seems like the problem could be related to `MemoryError`?

**Comment by Crista23** [comment]
Hi @HanGuo97 , thanks for your response. The input file for decoding --decode_data_dir decode/test_file.src contains just 1 line to be simplified, so it is strange indeed I get memory error on a 12 GB NVidia GPU. Can you please confirm the parameters to sample from the trained model are valid choices and that the decoding file can contain plain text? Thanks again!

        python run.py --mode decode --decode_ckpt_file NewselaFinalMTL/model-final --decode_data_dir decode/abc.txt --decode_output_file output.txt --log_root logs --exp_name test --soft_sharing_coef 0.1 --vocab_path cnn-dailymail/finished_files/vocab --batch_size 32 --beam_size 5 --max_enc_steps 5 --max_dec_steps 5 --steps_per_eval 5 --lr 0.01

**Comment by HanGuo97** [comment]
Not an expert in this, but seems like `MemoryError` is related to the CPU memory error not the GPU memory error -- which is not expected given that you only feed one line.

**Comment by Crista23** [comment]
Hi @HanGuo97 , I managed to overcome the memory error, but I am wondering if you can post the exact parameters to sample from your pre-trained model. When I run 
          
     python run.py --beam_size 5 --max_enc_steps 5 --max_dec_steps 5 --steps_per_eval 5 --lr 0.01 - -batch_size 128 --vocab_path MultitaskSimplification/vocab --decode_ckpt_file MultitaskSimplification/NewselaFinalMTL/model-final ----decode_data_dir text_simplification/text_simplification/model/text_simplification_data/turkcorpus/test.8turkers.tok.norm  --decode_output_file output.txt --log_root MultitaskSimplification/logs --exp_name testme --mode decode --soft_sharing_coef 0.1

results in the error below:

     InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [50000,128] rhs shape= [29131,128]
         [[Node: save_1/Assign_29 = Assign[T=DT_FLOAT, _class=["loc:@Newsela_WordEmb/embedding"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](Newsela_WordEmb/embedding, save_1/RestoreV2_29)]]

Can you share the parameters you trained your model with so that I can sample from your pre-trained model? Thanks!

**Comment by HanGuo97** [comment]
From the error messages, I don't think the errors are related to them. For decoding, many parameters are not used, some of them could be set simply as placeholders. But just in case this can be helpful, here are the parameters I used:

MAC_ENC_STEPS=60
MAX_DEC_STEPS=50
BEAM_SIZE=5
BATCH_SIZE=64
STEPS_PER_EVAL=500
LEARNING_RATE=0.001

By the way, I see `- -batch_size 128` in the code you pasted (should be `--`), not sure this could be the source of them problem though.

**Comment by Crista23** [comment]
Thanks for your response,  @HanGuo97! The sampling code does run now, it seems the error was causes by unmatching vocabulary size - the checkpointed model was expecting a vocabulary size of 29131 words. 

However, the code has been running for more than 10 hours and the output file does not contain any decoded sentences when specifying only 10 complex sentences as input for decoding. I also get the warning message below:

      WARNING:tensorflow:Bucket input queue is empty when calling next_batch. Bucket queue size: 0, Input queue size: 0

Do you know if this is normal for your pre-trained model, how much time should it take to decode from it? And does it accept input sentences specified in a plain text file one per line or does the input need to be further preprocessed? Thank you!

**Comment by Crista23** [comment]
Hi @HanGuo97, I finally managed to sample from your model when specifying *.bin files each made up of an abstract and article field. Can you please make available the Newsela vocab of 29,131 words which you used when training your pre-trained model?

**Comment by HanGuo97** [comment]
Glad it works for you! Unfortunately, it has been a while since I used the data, and all of the data has then been archived to a long-term storage filesystem as some of the servers are retiring; searching and reading from the disk is very slow and hard. That being said, I did manage to find a file at a different server with a similar filename (with size `29127`) but I never tested the file there. If you would like to give it a try, I can email it to you (and please let me know your email).

**Comment by Crista23** [comment]
Sure, I am interested in trying it! My email is g.c.garbacea@gmail.com, thank you so much!

**Comment by bhavikapanara** [comment]
@Crista23  

Where you get the vocab file? Or you have trained the model from scratch on your end.
